const logos = {
  atl: require('./assets/atl.png'),
  bos: require('./assets/bos.png'),
  bkn: require('./assets/bkn.png'),
  cha: require('./assets/cha.png'),
  chi: require('./assets/chi.png'),
  cle: require('./assets/cle.png'),
  dal: require('./assets/dal.png'),
  den: require('./assets/den.png'),
  det: require('./assets/det.png'),
  eastern: require('./assets/eastern.png'),
  gsw: require('./assets/gsw.png'),
  hou: require('./assets/hou.png'),
  ind: require('./assets/ind.png'),
  lac: require('./assets/lac.png'),
  lal: require('./assets/lal.png'),
  mem: require('./assets/mem.png'),
  mia: require('./assets/mia.png'),
  mil: require('./assets/mil.png'),
  min: require('./assets/min.png'),
  nop: require('./assets/nop.png'),
  nyk: require('./assets/nyk.png'),
  okc: require('./assets/okc.png'),
  orl: require('./assets/orl.png'),
  phi: require('./assets/phi.png'),
  phx: require('./assets/phx.png'),
  por: require('./assets/por.png'),
  sac: require('./assets/sac.png'),
  sas: require('./assets/sas.png'),
  tor: require('./assets/tor.png'),
  uta: require('./assets/uta.png'),
  was: require('./assets/was.png'),
  western: require('./assets/western.png'),
}

export default logos